services:
  infra:
    container_name: $CONTAINER_NAME
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=$ALPINE_VERSION
        - TERRAFORM_VERSION=$TERRAFORM_VERSION
        - TERRAGRUNT_VERSION=$TERRAGRUNT_VERSION
        - PACKER_VERSION=$PACKER_VERSION
        - GLIBC_URL=$GLIBC_URL
        - GLIBC_VERSION=$GLIBC_VERSION
        - UID=$UID
        - GID=$GID
    env_file:
      - .env
    environment:
      - AWS_REGION=$AWS_REGION
      - REMOTE_STATE_BUCKET=$REMOTE_STATE_BUCKET
      - REMOTE_STATE_PROFILE=$REMOTE_STATE_PROFILE
      - STATE_LOCK_DYNAMODB_TABLE=$STATE_LOCK_DYNAMODB_TABLE
    volumes:
      - $HOME/.aws:/opt/.aws:ro
      - .:/opt/infra-app
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    restart: unless-stopped
